# Generated by Django 2.2.7 on 2020-09-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0)),
                ('last_paid', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Account Balance',
                'verbose_name_plural': 'Account Balances',
                'ordering': ['holder', 'balance'],
            },
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CheckOut',
                'verbose_name_plural': 'CheckOuts',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('amount', models.FloatField()),
                ('has_paid', models.BooleanField(default=False)),
                ('payment_url', models.URLField()),
                ('status_url', models.URLField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='PaynowConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_id', models.CharField(max_length=4)),
                ('integration_key', models.CharField(max_length=38)),
            ],
            options={
                'verbose_name': 'Paynow Details',
                'verbose_name_plural': 'Paynow Details',
            },
        ),
    ]
